### ISSUE TITLE
3rd Party Call Back Driver

### ISSUE THREAD

**Issue by OuticNZ** [Smurf-IV/Liquesce#4]
Hey,  Looking at the 3rd party driver used it seems to come from Eldos [https://www.callbacktechnologies.com/](url)  They look like they have repackaged and on the surface are doing very similiar things to what this does.   Is there a difference?  Also what function purpose does this driver perform in this project?  Just wondering if it can be done without the 3rd party driver.

**Comment by Smurf-IV** [comment]
> Hey, Looking at the 3rd party driver used it seems to come from Eldos [https://www.callbacktechnologies.com/](url) 

That is correct
> They look like they have repackaged and on the surface are doing very similiar things to what this does.

They have, and I have not had time to keep up with the latest release, and rewrite the code to deal with the new features.

> Is there a difference? 

The Breakout of the different features within the CBFS Suite will now make it easier for developers to target functionality that they require.
>Also what function purpose does this driver perform in this project?

It allows the merging of physical drives appear as a single entity, regardless of their original sizes; i.e. the software using the drive appears to be an actual physical entity.
>  Just wondering if it can be done without the 3rd party driver.

Nope, need to get in earlier, before the OS abstracts the storage functionality away from the HAL.
